### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TriYangZhang** [smiles724/InstructBio#2]
Thanks your answer!
可以解释一下下面图面里代码运行的问题吗。
![image](https://github.com/smiles724/InstructBio/assets/129965099/5dcd1aec-adec-4e72-941e-3ba13be27bf9)
感谢！

**Comment by smiles724** [comment]
Hi, thanks for your inquiry. Which sort of algorithm did you intend to reproduce? I suppose you try to implement a conventional machine learning method such as Transformer and LSTM. However, I am afraid that I have deleted or changed some parts of those codes, and the codebase is mainly designed for GNNs. If you desire to run algorithms that are not based on graphs, please refer to the original MOLECULEACE github: https://github.com/molML/MoleculeACE 

However, if you strongly recommend me to update the code so that it supports all categories of approaches, please let me know.

**Comment by TriYangZhang** [comment]
sorry 
I try to python the teacher_main.py.But when it turn to 2/5fold, it turn wrong. it said keyerror :'mask'
I find in the 2 fold, it add the mask wrongly?

**Comment by smiles724** [comment]
> sorry I try to python the teacher_main.py.But when it turn to 2/5fold, it turn wrong. it said keyerror :'mask' I find in the 2 fold, it add the mask wrongly?



Thanks for the question. The problem is raised due to the modification of the x_train and y_train. Please change the splitting code to the following line. BTW, we are gonna update the codebase in the near future. Please wait for the update. 
`        x_tr_fold, y_tr_fold = [copy.deepcopy(x_train[i]) for i in split['train_idx']], [copy.deepcopy(y_train[i]) for i in split['train_idx']]
        x_val_fold, y_val_fold = [copy.deepcopy(x_train[i]) for i in split['val_idx']], [copy.deepcopy(y_train[i]) for i in split['val_idx']]`
